spring.application.name=user-managment-service-twitterlike

logging.level.com.masterilidan.usermanagmentservicetwitterlike=DEBUG
logging.level.web=DEBUG


spring.datasource.url=jdbc:postgresql://localhost:5432/user_database
spring.data.jdbc.dialect=h2
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

url.baseUrl.UserService=localhost:8080
url.baseUrl.MessageService=localhost:8081
url.baseUrl.SubsService=localhost:8082