spring.application.name=user-managment-service-twitterlike

logging.level.root=INFO

spring.datasource.url=jdbc:postgresql://192.168.0.141:5432/user_database
spring.data.jdbc.dialect=h2
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver